version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    volumes:
      - model_volume:/usr/src/app/model
    ports:
      - "8000:8000"

volumes:
  model_volume: